### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by MrTarantula** [bodhisatwag/foundation-angular-datepicker#1]
It would be great if you published this to NPM!

**Comment by bodhisatwag** [comment]
Should I publish this in NPM or Bower? Its a front-end thing actually.

**Comment by MrTarantula** [comment]
Pushing to both will get you the most exposure. I am trying to only use NPM for the project I'm currently working on. Angular and others have NPM packages, but for most people Bower is preferred for front-end.

**Comment by bodhisatwag** [comment]
Okay I will then do for both.

On Fri, Dec 11, 2015 at 10:39 PM, MrTarantula notifications@github.com
wrote:

> Pushing to both will get you the most exposure. I am trying to only use
> NPM for the project I'm currently working on, Angular and others have NPM
> packages, but for most people Bower is preferred for front-end.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bodhisatwag/foundation-angular-datepicker/issues/1#issuecomment-163992940
> .

## 

Thanks & Regards,
Bodhisatwa Ghosh

**Comment by setaou** [comment]
I would also be interested in having your package available on Bower. Do you need help with that ?

**Comment by GideonPARANOID** [comment]
Any progress on this? Would be really useful.
